In [1]:
import numpy as np

In [2]:
#array
v=np.array([1,4,3,1,5],dtype='float')
w=np.array([1,4,0,1,-5])
print(v)
print(w)
print(type(v))

[1. 4. 3. 1. 5.]
[ 1  4  0  1 -5]
<class 'numpy.ndarray'>


In [3]:
v.max()

5.0

In [4]:
v.sum()

14.0

In [5]:
v.dot(w)

-7.0

In [6]:
np.dot(v,w)

-7.0

In [7]:
np.sin(v)

array([ 0.84147098, -0.7568025 ,  0.14112001,  0.84147098, -0.95892427])

In [8]:
v+1

array([2., 5., 4., 2., 6.])

In [9]:
v*2

array([ 2.,  8.,  6.,  2., 10.])

In [10]:
v**2

array([ 1., 16.,  9.,  1., 25.])

In [11]:
A=np.array([[1,2,0],[np.pi,0,np.sqrt(5)],[0,0,1]])

In [12]:
x=np.ones(4)
print(A)
print(x)

[[1.         2.         0.        ]
 [3.14159265 0.         2.23606798]
 [0.         0.         1.        ]]
[1. 1. 1. 1.]


In [13]:
np.dot(A,x)

ValueError: shapes (3,3) and (4,) not aligned: 3 (dim 1) != 4 (dim 0)

In [14]:
A.shape

(3, 3)

In [15]:
x.shape

(4,)

In [16]:
x=np.ones((3,1))
print(x)

[[1.]
 [1.]
 [1.]]


In [17]:
x.shape

(3, 1)

In [18]:
b=np.dot(A,x)
b.shape

(3, 1)

In [19]:
y=np.ones((1,3))
print(y)

[[1. 1. 1.]]


In [20]:
np.dot(A,y.T)

array([[3.        ],
       [5.37766063],
       [1.        ]])

In [21]:
A

array([[1.        , 2.        , 0.        ],
       [3.14159265, 0.        , 2.23606798],
       [0.        , 0.        , 1.        ]])

In [22]:
A.T

array([[1.        , 3.14159265, 0.        ],
       [2.        , 0.        , 0.        ],
       [0.        , 2.23606798, 1.        ]])

In [23]:
np.linalg.det(A)

-6.283185307179585

In [24]:
np.dot(np.linalg.inv(A),b)

array([[1.],
       [1.],
       [1.]])

In [25]:
x=np.arange(0,100)
print(x.shape)

(100,)


In [26]:
x=x.reshape((5,5,4))
x.shape

(5, 5, 4)

In [27]:
x2=x.flatten()
x2.shape

(100,)

In [28]:
np.concatenate(([1,2],[3,4],[3]))

array([1, 2, 3, 4, 3])

In [29]:
a=np.ones((2,2))
b=np.eye(2)
np.concatenate((a,b))

array([[1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.]])

In [30]:
np.concatenate((a,b),axis=1)

array([[1., 1., 1., 0.],
       [1., 1., 0., 1.]])

In [31]:
np.concatenate((a,b),axis=0)

array([[1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.]])

In [32]:
a.shape

(2, 2)